apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: member-service
  annotations:
    harness.io/pipelines: |
      Build: https://laxmiharness.pr2.harness.io/ng/account/6cBjZs_fTWCiRITqFyRrgQ/module/ci/orgs/default/projects/IDP/pipelines/CI_pipeline/pipeline-studio?storeType=INLINE
  tags:
    - java
    - food-ordering
    - four
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  system: delivery
